apiVersion: apps/v1
kind: Deployment
metadata:
  name: toggle-service
  labels:
    app: toggle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toggle-service
  template:
    metadata:
      labels:
        app: toggle-service
    spec:
      containers:
      - name: toggle-service
        image: nginx:latest
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: toggle-service
spec:
  selector:
    app: toggle-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
