# OpenTelemetry Collector Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http
    exporters:
      prometheus:
      loki:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [loki]
