name: Self-Healing Workflow

on:
  repository_dispatch:
    types: [alert-trigger]

jobs:
  restart-service:
    runs-on: ubuntu-latest
    steps:
      - name: Reiniciar Auth Service
        run: kubectl rollout restart deployment/auth-service
