name: Update GitOps

on:
  workflow_dispatch:   # você roda manualmente

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Atualizar tag da imagem
        run: |
          sed -i 's|image:.*auth-service:.*|image: "950185226544.dkr.ecr.us-east-1.amazonaws.com/togglemaster/auth-service:1.0.1"|' FIAP/gitops/applications/auth-service/deployment.yaml

      - name: Commit e Push
        run: |
          git add FIAP/gitops/applications/auth-service/deployment.yaml
          git commit -m "Atualiza tag da imagem para 1.0.1"
          git push origin HEAD:main
